// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Page: typeof import('./src/components/page.vue')['default']
    PostMeta: typeof import('./src/components/post-meta.vue')['default']
    Toast: typeof import('./src/components/toast.vue')['default']
  }
}

export { }
