name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  labels:
    name: Labels
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Labeler
        uses: actions/labeler@v5
        with:
          dot: true

  test:
    runs-on: ubuntu-latest
    name: Test

    env:
      APP_NAME: 'Admin App'
      BASE_URL: 'https://admin.feryardiant.id/'
      PROJECT_ID: 'fery-wardiyanto'
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_EMULATORS_PATH: ${{ github.workspace }}/.firebase
      RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
      RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache Emulators
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: .firebase
          key: firebase-emulators

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Test
        run: pnpm test -- --project ${{ env.PROJECT_ID }}
